### ISSUE TITLE
Copying code segments from ballerina-by-example also copy accompanying text

### ISSUE THREAD

**Issue by chintana** [ballerinalang/website#158]
When selecting code segments it selects accompanying text also. This prevent copy paste run cycle and you need to manually remove added text. See below,

<img width="766" alt="bbe-selection" src="https://user-images.githubusercontent.com/27903/28655065-f534f622-724d-11e7-9f06-b743226c3a6b.png">

**Comment by madhuramendis** [comment]
This is fixed now

**Comment by pubudu91** [comment]
This issue is still there
