### ISSUE TITLE
Copy-to-clipboard in Ballerina by Examples not working properly

### ISSUE THREAD

**Issue by pubudu91** [ballerinalang/website#161]
The copy-to-clipboard option doesn't copy the whole code. It only copies the particular code in the table cell. The copy-to-clipboard button appears for each of the table cells where there is code. Ideally, the button should copy the whole code and should only appear on the top most cell containing the code.

**Comment by madhuramendis** [comment]
This is fixed now

**Comment by madhuramendis** [comment]
This is fixed now
